### ISSUE TITLE
Does this tool test in html files also ?

### ISSUE THREAD

**Issue by pirahana** [mgechev/ng-template#1]
Hi,
  Thanks for the awesome tool. But I had a query that is :
When specifying the path to ngmigrate,  I give the complete path. In the example it show we give path to *.ts, does this mean that only ts(typescript) files are investigated or does in look into the html files also.
In my project I have <template> used in html file and it is not able to look into it.
The command i used is : 
ngmigrate E:\My-Project\Project\component-lib\src\*\*.ts

**Comment by mgechev** [comment]
Answered over email:

> If the template is not referenced in the code, or it is referenced but not as a string literal value of the properties `template` or `templateUrl` of the object passed to the `@Component` decorator, codelyzer (and respectively ngmigrate) won’t be able to find it and process it.
> 
> Also:
> 
> ```ts
> // will work
> 
> @Component({
>   templateUrl: 'foo.html'
> })
> class Foo {}
> ```
> 
> ```ts
> // will not work
> 
> const metadata = {
>   templateUrl: 'foo.html'
> };
> @Component(metadata)
> class Foo {}
> ```
